config/routes.rb
Kitty::Application.routes.draw do
  get "/auth/:provider/callback", to: "users#create"
  get "/auth/failure", to: redirect("/")

  delete "signout", to: "users#destroy", as: "signout"
  root "users#index"

end

app/models/user.rb
class User < ActiveRecord::Base
  def self.from_auth(auth)
    User.where(auth.slice(:provider, :uid)).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.email =  auth.info.email
      user.avatar = auth.info.image
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def create
    user = User.from_auth(env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to root_url
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Kitty</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="nav-wrapper">
    <div class="nav">
      <% if current_user %>
        <%= image_tag current_user.avatar, size: "30x30" %>
        <strong><%= current_user.name %></strong>
        <%= link_to "退出", signout_path, :method => :delete %>
      <% else %>
        <%= link_to "Linkedin 账户登录", "/auth/linkedin" %>
      <% end %>
    </div>
  </div>
  <div class="container">
    <%= yield %>
  </div>
</body>
</html>

app/views/users/index.html.erb
<ul>
  <% if @users.present? %>
    <% @users.each do |user| %>
      <li>
        <span><%= image_tag user.avatar, size: '50x50' %></span>
        <span><%= user.name %></span>
        <%= user.email %>
      </li>
    <% end %>
  <% end %>
</ul>